name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Optional but helpful for speed
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', 'mkdocs.yml') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install MkDocs and any themes/plugins you use:
          pip install mkdocs
          # If you use a theme/plugins, uncomment:
          # pip install mkdocs-material mkdocs-minify-plugin mkdocs-awesome-pages-plugin

      - name: Show MkDocs & config versions
        run: |
          mkdocs --version
          echo "---- mkdocs.yml ----"
          sed -n '1,200p' mkdocs.yml || true

      # If your previous run failed, start clean
      - name: Clean previous site dir
        run: rm -rf site

      - name: Build site (strict)
        run: mkdocs build --strict
        # If this step fails, fix mkdocs.yml (nav paths, missing files, bad YAML)
        # For quick confirmation, try: mkdocs build  (without --strict)

      - name: List build output
        run: |
          test -f site/index.html || (echo "index.html missing in site/"; exit 1)
          ls -lah site | head -n 50

      - name: Add CNAME for custom domain
        # Set your domain here:
        run: echo your.domain.com > site/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Redundant but fine; deploy action will also set CNAME if given:
          cname: themodeldatabase.com

